<<<<<<<< inlined_totsc/endch4.baf
IF
  Entered([PC])
  Dead("Davaeorn")  // Davaeorn
  Global("Chapter","GLOBAL",4)
THEN
  RESPONSE #100
    RevealAreaOnMap("AR0900")
    IncrementChapter("Chptxt5")
    AddJournalEntry(15839)
END

IF
  Entered([PC])
THEN
  RESPONSE #100
    SmallWait(1)
END
>>>>>>>>
COMPILE ~inlined_totsc/endch4.baf~

COPY_EXISTING ~ar1803.are~ ~override~
 WRITE_ASCII 0x94 ~~ (8)
BUT_ONLY_IF_IT_CHANGES